Repository MDAnalysis/mdanalysis, pull requests merged in 2018-07, with the labels that each got.

#1967 updated GitHub template for issues
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
Labels: policy

#1728 Continuous Chain Reader
  package/CHANGELOG
  package/MDAnalysis/coordinates/chain.py
  package/MDAnalysis/core/universe.py
  testsuite/MDAnalysisTests/coordinates/test_chainreader.py
  testsuite/MDAnalysisTests/util.py
Labels: API, Component-Readers, usability

#1980 switched from coverall to codecov
  .travis.yml
  README.rst
  package/SUMMARY.txt
  testsuite/README
  testsuite/setup.py
Labels: Continuous Integration, Work in progress

#2002 TST: test_unique_int_1d now enforces int64 type
  testsuite/MDAnalysisTests/lib/test_cutil.py
Labels: OpSys-Windows

#2009 BUG: fix several Windows test failures with int64 type enforcement
  package/MDAnalysis/core/selection.py
Labels: OpSys-Windows

#2014 BUG: fix Windows file permission setting in test_universe
  testsuite/MDAnalysisTests/core/test_universe.py
Labels: OpSys-Windows

#2015 BUG: test_persistent_offsets_readonly Windows fix
  testsuite/MDAnalysisTests/coordinates/test_xdr.py
Labels: OpSys-Windows
