Repository MDAnalysis/mdanalysis, pull requests merged in 2018-05, with the labels that each got.

#1672 BLD / MAINT: Improve Windows Compatibility -- first batch of changes
  package/CHANGELOG
  package/MDAnalysis/analysis/encore/clustering/include/ap.h
  package/MDAnalysis/analysis/encore/clustering/src/ap.c
  package/MDAnalysis/analysis/encore/dimensionality_reduction/src/spe.c
  package/MDAnalysis/coordinates/PDB.py
  package/MDAnalysis/core/universe.py
  package/MDAnalysis/lib/c_distances.pyx
  package/MDAnalysis/lib/formats/include/fastio.h
  package/MDAnalysis/lib/formats/libdcd.pyx
  package/MDAnalysis/lib/formats/src/xdrfile.c
  package/MDAnalysis/lib/include/calc_distances.h
  package/setup.py
  testsuite/MDAnalysisTests/analysis/test_hydrogenbondautocorrel.py
  testsuite/MDAnalysisTests/coordinates/test_pdb.py
  testsuite/MDAnalysisTests/coordinates/test_trz.py
  testsuite/MDAnalysisTests/core/test_atomselections.py
  testsuite/MDAnalysisTests/lib/test_util.py
  testsuite/MDAnalysisTests/utils/test_streamio.py
  testsuite/setup.py
Labels: OpSys-Windows, installation

#1905 MAINT / CI: add missing imports flagged by pylint; Fixes Issue #1904.
  package/MDAnalysis/analysis/hbonds/wbridge_analysis.py
  package/MDAnalysis/due.py
  testsuite/MDAnalysisTests/analysis/test_distances.py
  testsuite/MDAnalysisTests/analysis/test_wbridge.py
  testsuite/MDAnalysisTests/core/test_groups.py
  testsuite/MDAnalysisTests/lib/test_distances.py
  testsuite/MDAnalysisTests/visualization/test_streamlines.py
Labels: Continuous Integration

#1880 BLD: Adding MDA appveyor CI test for Python 3.6
  .appveyor.yml
Labels: OpSys-Windows, Work in progress

#1910 BUG: duecredit should now be imported properly on Windows
  package/MDAnalysis/due.py
Labels: OpSys-Windows, defect

#1916 TST: improve Win compatibility of lammps DCD writer testing
  testsuite/MDAnalysisTests/coordinates/test_lammps.py
Labels: OpSys-Windows, testing

#1815 add new analysis.rdf_s module for calculating rdf seperately
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/__init__.py
  package/MDAnalysis/analysis/rdf.py
  package/doc/sphinx/source/documentation_pages/analysis/rdf.rst
  testsuite/MDAnalysisTests/analysis/test_rdf_s.py
  testsuite/MDAnalysisTests/data/analysis/YiiP_lipids.gro.gz
  testsuite/MDAnalysisTests/data/analysis/YiiP_lipids.xtc
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/setup.py
Labels: Component-Analysis

#1914 TST: skip gsd-based tests on Windows
  testsuite/MDAnalysisTests/coordinates/test_gsd.py
  testsuite/MDAnalysisTests/topology/test_gsd.py
Labels: OpSys-Windows, testing

#1924 BUG: libdcd now properly handles missing input file on Windows
  package/MDAnalysis/lib/formats/libdcd.pyx
Labels: OpSys-Windows
