Repository MDAnalysis/mdanalysis, pull requests merged in 2019-12, with the labels that each got.

#2415 TST: add Python 3.8 Linux to CI
  .travis.yml
Labels: testing

#2416 TST: add Windows Python 3.8 to CI
  .appveyor.yml
Labels: OpSys-Windows, testing

#2419 Bugfix/issue 2413 traj stride
  package/CHANGELOG
  package/MDAnalysis/coordinates/base.py
  testsuite/MDAnalysisTests/coordinates/test_reader_api.py
Labels: Component-Readers
