Repository MDAnalysis/mdanalysis, pull requests merged in 2019-04, with the labels that each got.

#2234 fix travis file (tab -> space)
  .travis.yml
Labels: Component-Docs, testing

#2226 Survival probability: Intermittency, Step, Residues, Overlapping SP Selection Example
  package/CHANGELOG
  package/MDAnalysis/analysis/waterdynamics.py
  testsuite/MDAnalysisTests/analysis/test_waterdynamics.py
Labels: Component-Analysis

#2244 TST: add backup pytest for MacOS CI
  .travis.yml
Labels: testing

#2239 Addresses failure of `test_load()` in PSA (#2049)
  package/MDAnalysis/analysis/psa.py
  testsuite/MDAnalysisTests/analysis/test_psa.py
Labels: Component-Analysis

#2257 MAINT: compensate for NumPy load change
  package/MDAnalysis/analysis/encore/utils.py
Labels: maintainability, testing
