Repository MDAnalysis/mdanalysis, pull requests merged in 2020-05, with the labels that each got.

#2680 BUG: allow repeated mol2 writes
  package/MDAnalysis/coordinates/MOL2.py
  testsuite/MDAnalysisTests/coordinates/test_mol2.py
Labels: Component-Writers, defect

#2682 MAINT, TST: remove tempdir
  testsuite/MDAnalysisTests/analysis/test_align.py
  testsuite/MDAnalysisTests/analysis/test_contacts.py
  testsuite/MDAnalysisTests/coordinates/base.py
  testsuite/MDAnalysisTests/coordinates/test_chemfiles.py
  testsuite/MDAnalysisTests/coordinates/test_gro.py
  testsuite/MDAnalysisTests/coordinates/test_mol2.py
  testsuite/MDAnalysisTests/coordinates/test_pdb.py
  testsuite/MDAnalysisTests/coordinates/test_pqr.py
  testsuite/MDAnalysisTests/coordinates/test_xdr.py
  testsuite/MDAnalysisTests/coordinates/test_xyz.py
  testsuite/MDAnalysisTests/core/test_universe.py
  testsuite/MDAnalysisTests/tempdir.py
  testsuite/MDAnalysisTests/utils/test_streamio.py
Labels: maintainability, testing

#2613 Added PCA subspace comparison methods and fixed n_components selection
  package/CHANGELOG
  package/MDAnalysis/analysis/pca.py
  package/doc/sphinx/source/documentation_pages/references.rst
  testsuite/MDAnalysisTests/analysis/test_pca.py
Labels: Component-Analysis, enhancement

#2696 CI: add 32-bit Win to CI
  azure-pipelines.yml
  package/CHANGELOG
  package/MDAnalysis/core/selection.py
  package/MDAnalysis/core/topologyattrs.py
  package/MDAnalysis/lib/NeighborSearch.py
  package/MDAnalysis/lib/_augment.pyx
  package/MDAnalysis/lib/_cutil.pyx
  package/MDAnalysis/lib/distances.py
  package/MDAnalysis/lib/nsgrid.pyx
  package/MDAnalysis/lib/pkdtree.py
  testsuite/MDAnalysisTests/analysis/test_density.py
  testsuite/MDAnalysisTests/analysis/test_hole2.py
  testsuite/MDAnalysisTests/core/test_fragments.py
  testsuite/MDAnalysisTests/formats/test_libdcd.py
  testsuite/MDAnalysisTests/lib/test_augment.py
  testsuite/MDAnalysisTests/lib/test_cutil.py
  testsuite/MDAnalysisTests/lib/test_distances.py
  testsuite/MDAnalysisTests/topology/test_tprparser.py
Labels: 32 bit, Continuous Integration, OpSys-Windows
