Repository MDAnalysis/mdanalysis, pull requests merged in 2020-02, with the labels that each got.

#2411 Bugfix #2410
  package/MDAnalysis/auxiliary/base.py
  testsuite/MDAnalysisTests/auxiliary/base.py
Labels: Work in progress

#2485 I/O for namd binary coordinate format
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/coordinates/NAMDBIN.py
  package/MDAnalysis/coordinates/__init__.py
  package/doc/sphinx/source/documentation_pages/coordinates/NAMDBIN.rst
  package/doc/sphinx/source/documentation_pages/coordinates_modules.rst
  testsuite/MDAnalysisTests/coordinates/test_namdbin.py
  testsuite/MDAnalysisTests/data/adk_open.coor
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/setup.py
Labels: Format-CHARMM/NAMD, enhancement

#2322 Tidying Universe.__init__
  package/CHANGELOG
  package/MDAnalysis/core/universe.py
  testsuite/MDAnalysisTests/core/test_universe.py
  testsuite/MDAnalysisTests/topology/test_top.py
Labels: wait-python3

#2544 BENCH: fix benchmark suite
  benchmarks/benchmarks/ag_methods.py
  benchmarks/benchmarks/analysis/rdf.py
Labels: performance

#2477 Move parmed to optional dependency
  .travis.yml
  package/MDAnalysis/coordinates/ParmEd.py
  package/MDAnalysis/core/_get_readers.py
  package/setup.py
  testsuite/MDAnalysisTests/coordinates/test_parmed.py
  testsuite/MDAnalysisTests/topology/test_parmed.py
Labels: installation

#2546 TST, BENCH: add asv check to Travis CI
  .travis.yml
Labels: performance, testing

#2559 Update links to wiki pages
  package/AUTHORS
  package/INSTALL
  package/MDAnalysis/tests/__init__.py
  package/MDAnalysis/version.py
  package/README
  package/doc/sphinx/source/index.rst
  testsuite/MDAnalysisTests/utils/test_meta.py
Labels: Component-Docs, GSOC Starter
