Repository MDAnalysis/mdanalysis, pull requests merged in 2020-07, with the labels that each got.

#2829 MAINT: fixes for NumPy master
  package/MDAnalysis/core/selection.py
  package/MDAnalysis/topology/base.py
Labels: maintainability

#2834 MAINT: comprehensive type alias cleanup
  package/CHANGELOG
  package/MDAnalysis/analysis/hydrogenbonds/hbond_analysis.py
  package/MDAnalysis/coordinates/CRD.py
  package/MDAnalysis/coordinates/base.py
  package/MDAnalysis/core/selection.py
  package/MDAnalysis/core/topologyobjects.py
  package/MDAnalysis/lib/nsgrid.pyx
  package/MDAnalysis/topology/MMTFParser.py
  package/MDAnalysis/topology/PDBParser.py
  package/MDAnalysis/topology/TXYZParser.py
  testsuite/MDAnalysisTests/analysis/test_align.py
  testsuite/MDAnalysisTests/analysis/test_distances.py
  testsuite/MDAnalysisTests/core/test_topology.py
  testsuite/setup.cfg
Labels: maintainability

#2836 MAINT: master -> main where possible
  package/MDAnalysis/analysis/hbonds/hbond_autocorrel.py
  package/MDAnalysis/core/selection.py
  package/MDAnalysis/core/universe.py
  testsuite/MDAnalysisTests/core/test_atomgroup.py
Labels: maintainability

#2838 MAINT: use modern ConfigParser
  package/setup.py
Labels: installation, maintainability

#2842 Removing the deprecated module, see PR #2791 for more info.
  package/CHANGELOG
  package/MDAnalysis/analysis/hydrogenbonds/hbond_analysis.py
  package/MDAnalysis/analysis/waterdynamics.py
  testsuite/MDAnalysisTests/analysis/test_waterdynamics.py
Labels: remove-2.0

#2850 CI: migrate to Azure for Win
  azure-pipelines.yml
Labels: Continuous Integration, OpSys-Windows

#2840 Spring cleaning for the TPR parser
  package/CHANGELOG
  package/MDAnalysis/topology/TPRParser.py
  package/MDAnalysis/topology/tpr/obj.py
  package/MDAnalysis/topology/tpr/utils.py
  testsuite/MDAnalysisTests/data/tprs/2lyz_gmx_2020_double.tpr
  testsuite/MDAnalysisTests/data/tprs/all_bonded/dummy_2020_double.tpr
  testsuite/MDAnalysisTests/data/tprs/all_bonded/dummy_3.3.4.top
  testsuite/MDAnalysisTests/data/tprs/all_bonded/dummy_3.3.4.tpr
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/dummy.gro
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/dummy.top
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/dummy_2018.mdp
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/dummy_2020.mdp
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/dummy_4.0.7.mdp
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/dummy_4.0.7.top
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/extra-interactions-2016.3.tpr
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/extra-interactions-2018.tpr
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/extra-interactions-2020.tpr
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/extra-interactions-4.0.7.tpr
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/MDAnalysisTests/topology/test_tprparser.py
Labels: Component-Topology, Format-Gromacs, maintainability

#2845 MAINT: explicit ragged arrays
  package/MDAnalysis/analysis/rms.py
  package/MDAnalysis/core/topologyattrs.py
  package/MDAnalysis/lib/util.py
  testsuite/MDAnalysisTests/core/test_topology.py
  testsuite/setup.cfg
Labels: maintainability

#2858 Add elements attribute to TPR parser
  package/CHANGELOG
  package/MDAnalysis/topology/TPRParser.py
  package/MDAnalysis/topology/tpr/obj.py
  package/MDAnalysis/topology/tpr/utils.py
  testsuite/MDAnalysisTests/topology/base.py
  testsuite/MDAnalysisTests/topology/test_tprparser.py
Labels: Component-Topology, Format-Gromacs

#2872 Implemented extraction of chains from DMS formats
  package/CHANGELOG
  package/MDAnalysis/topology/DMSParser.py
  testsuite/MDAnalysisTests/data/adk_closed_domains.dms
  testsuite/MDAnalysisTests/data/adk_closed_no_segid.dms
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/MDAnalysisTests/topology/test_dms.py
Labels: Format-Desmond
