Repository MDAnalysis/mdanalysis, pull requests merged in 2020-08, with the labels that each got.

#2723 Serialize FileIO and TextIOWrapper and Universe
  package/CHANGELOG
  package/MDAnalysis/coordinates/DLPoly.py
  package/MDAnalysis/coordinates/GSD.py
  package/MDAnalysis/coordinates/TRJ.py
  package/MDAnalysis/coordinates/base.py
  package/MDAnalysis/coordinates/chain.py
  package/MDAnalysis/coordinates/chemfiles.py
  package/MDAnalysis/core/universe.py
  package/MDAnalysis/lib/__init__.py
  package/MDAnalysis/lib/formats/libdcd.pyx
  package/MDAnalysis/lib/formats/libmdaxdr.pyx
  package/MDAnalysis/lib/picklable_file_io.py
  package/MDAnalysis/lib/util.py
  package/doc/sphinx/source/documentation_pages/coordinates/pickle_readers.rst
  package/doc/sphinx/source/documentation_pages/coordinates_modules.rst
  package/doc/sphinx/source/documentation_pages/lib/picklable_file_io.rst
  package/doc/sphinx/source/documentation_pages/lib_modules.rst
  testsuite/MDAnalysisTests/coordinates/base.py
  testsuite/MDAnalysisTests/core/test_universe.py
  testsuite/MDAnalysisTests/data/example_longer.gsd
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/MDAnalysisTests/parallelism/test_multiprocessing.py
  testsuite/MDAnalysisTests/utils/test_pickleio.py
Labels: GSoC, enhancement

#2894 Make H5MD serialize with pickle
  package/CHANGELOG
  package/MDAnalysis/coordinates/H5MD.py
  package/doc/sphinx/source/documentation_pages/coordinates/pickle_readers.rst
  testsuite/MDAnalysisTests/utils/test_pickleio.py
Labels: NSF REU

#2904 Replace deprecated imp
  package/MDAnalysis/coordinates/chemfiles.py
Labels: GSoC

#2911 DCD XDR pickle tests
  package/CHANGELOG
  package/MDAnalysis/lib/formats/libdcd.pyx
  package/MDAnalysis/lib/formats/libmdaxdr.pyx
  testsuite/MDAnalysisTests/formats/test_libdcd.py
  testsuite/MDAnalysisTests/formats/test_libmdaxdr.py
Labels: GSoC

#2755 Faster name selections
  package/CHANGELOG
  package/MDAnalysis/core/selection.py
  package/MDAnalysis/core/topologyattrs.py
  testsuite/MDAnalysisTests/core/test_atomselections.py
  testsuite/MDAnalysisTests/core/test_segmentgroup.py
  testsuite/MDAnalysisTests/core/test_topologyattrs.py
Labels: Component-Core, Component-Selections, performance

#2883 Add SMARTS selection
  package/MDAnalysis/core/groups.py
  package/MDAnalysis/core/selection.py
  package/doc/sphinx/source/documentation_pages/selections.rst
  testsuite/MDAnalysisTests/core/test_atomselections.py
Labels: GSoC
