Repository MDAnalysis/mdanalysis, pull requests merged in 2020-06, with the labels that each got.

#2685 Fix #2679
  package/CHANGELOG
  package/MDAnalysis/coordinates/PDB.py
  testsuite/MDAnalysisTests/analysis/test_hole2.py
  testsuite/MDAnalysisTests/coordinates/test_pdb.py
  testsuite/MDAnalysisTests/data/6QYR.mmtf.gz
  testsuite/MDAnalysisTests/datafiles.py
Labels: Component-Writers, Format-PDB

#2705 FHI-AIMS
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/coordinates/FHIAIMS.py
  package/MDAnalysis/coordinates/__init__.py
  package/MDAnalysis/topology/FHIAIMSParser.py
  package/MDAnalysis/topology/__init__.py
  package/doc/sphinx/source/documentation_pages/coordinates/FHIAIMS.rst
  package/doc/sphinx/source/documentation_pages/coordinates_modules.rst
  package/doc/sphinx/source/documentation_pages/topology/FHIAIMSParser.rst
  package/doc/sphinx/source/documentation_pages/topology/GSDParser.rst
  package/doc/sphinx/source/documentation_pages/topology_modules.rst
  testsuite/MDAnalysisTests/coordinates/reference.py
  testsuite/MDAnalysisTests/coordinates/test_fhiaims.py
  testsuite/MDAnalysisTests/data/fhiaims.in
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/MDAnalysisTests/topology/test_fhiaims.py
Labels: Component-Readers, Component-Topology, Component-Writers, enhancement

#2665 Issue 2656 nsgrid segfault
  package/CHANGELOG
  package/MDAnalysis/lib/nsgrid.pyx
  testsuite/MDAnalysisTests/lib/test_nsgrid.py
Labels: Component-lib, defect

#2713 CI: enable more win32 Azure tests
  azure-pipelines.yml
Labels: 32 bit, Continuous Integration, OpSys-Windows, maintainability

#2110 WIP Issue 2043 deprecate ts write
  package/CHANGELOG
  package/MDAnalysis/coordinates/DCD.py
  package/MDAnalysis/coordinates/FHIAIMS.py
  package/MDAnalysis/coordinates/GRO.py
  package/MDAnalysis/coordinates/MOL2.py
  package/MDAnalysis/coordinates/NAMDBIN.py
  package/MDAnalysis/coordinates/PDB.py
  package/MDAnalysis/coordinates/TRJ.py
  package/MDAnalysis/coordinates/TRR.py
  package/MDAnalysis/coordinates/TRZ.py
  package/MDAnalysis/coordinates/XDR.py
  package/MDAnalysis/coordinates/XTC.py
  package/MDAnalysis/coordinates/XYZ.py
  package/MDAnalysis/coordinates/__init__.py
  package/MDAnalysis/coordinates/base.py
  package/MDAnalysis/coordinates/chemfiles.py
  package/MDAnalysis/coordinates/null.py
  testsuite/MDAnalysisTests/coordinates/test_chemfiles.py
  testsuite/MDAnalysisTests/coordinates/test_dcd.py
  testsuite/MDAnalysisTests/coordinates/test_lammps.py
  testsuite/MDAnalysisTests/coordinates/test_netcdf.py
  testsuite/MDAnalysisTests/coordinates/test_trz.py
  testsuite/MDAnalysisTests/coordinates/test_writer_api.py
  testsuite/MDAnalysisTests/coordinates/test_xdr.py
Labels: Work in progress

#2754 Remove ts from writers
  package/CHANGELOG
  package/MDAnalysis/coordinates/CRD.py
  package/MDAnalysis/coordinates/DCD.py
  package/MDAnalysis/coordinates/FHIAIMS.py
  package/MDAnalysis/coordinates/GRO.py
  package/MDAnalysis/coordinates/MOL2.py
  package/MDAnalysis/coordinates/NAMDBIN.py
  package/MDAnalysis/coordinates/PDBQT.py
  package/MDAnalysis/coordinates/PQR.py
  package/MDAnalysis/coordinates/TRJ.py
  package/MDAnalysis/coordinates/TRR.py
  package/MDAnalysis/coordinates/TRZ.py
  package/MDAnalysis/coordinates/XTC.py
  package/MDAnalysis/coordinates/XYZ.py
  package/MDAnalysis/coordinates/base.py
  package/MDAnalysis/coordinates/chemfiles.py
  package/MDAnalysis/coordinates/null.py
  testsuite/MDAnalysisTests/coordinates/base.py
  testsuite/MDAnalysisTests/coordinates/test_chainreader.py
  testsuite/MDAnalysisTests/coordinates/test_dcd.py
  testsuite/MDAnalysisTests/coordinates/test_lammps.py
  testsuite/MDAnalysisTests/coordinates/test_netcdf.py
  testsuite/MDAnalysisTests/coordinates/test_null.py
  testsuite/MDAnalysisTests/coordinates/test_trz.py
  testsuite/MDAnalysisTests/coordinates/test_writer_api.py
  testsuite/MDAnalysisTests/coordinates/test_xdr.py
  testsuite/MDAnalysisTests/coordinates/test_xyz.py
Labels: remove-2.0

#2756 Remove py2 things from core
  package/MDAnalysis/core/__init__.py
  package/MDAnalysis/core/_get_readers.py
  package/MDAnalysis/core/groups.py
  package/MDAnalysis/core/selection.py
  package/MDAnalysis/core/topology.py
  package/MDAnalysis/core/topologyattrs.py
  package/MDAnalysis/core/topologyobjects.py
  package/MDAnalysis/core/universe.py
  testsuite/MDAnalysisTests/core/test_accumulate.py
  testsuite/MDAnalysisTests/core/test_atom.py
  testsuite/MDAnalysisTests/core/test_atomgroup.py
  testsuite/MDAnalysisTests/core/test_atomselections.py
  testsuite/MDAnalysisTests/core/test_copying.py
  testsuite/MDAnalysisTests/core/test_fragments.py
  testsuite/MDAnalysisTests/core/test_group_traj_access.py
  testsuite/MDAnalysisTests/core/test_groups.py
  testsuite/MDAnalysisTests/core/test_index_dtype.py
  testsuite/MDAnalysisTests/core/test_requires.py
  testsuite/MDAnalysisTests/core/test_residue.py
  testsuite/MDAnalysisTests/core/test_residuegroup.py
  testsuite/MDAnalysisTests/core/test_segment.py
  testsuite/MDAnalysisTests/core/test_segmentgroup.py
  testsuite/MDAnalysisTests/core/test_topology.py
  testsuite/MDAnalysisTests/core/test_topologyattrs.py
  testsuite/MDAnalysisTests/core/test_topologyobjects.py
  testsuite/MDAnalysisTests/core/test_universe.py
  testsuite/MDAnalysisTests/core/test_unwrap.py
  testsuite/MDAnalysisTests/core/test_updating_atomgroup.py
  testsuite/MDAnalysisTests/core/test_wrap.py
  testsuite/MDAnalysisTests/core/util.py
Labels: remove-2.0

#2619 Add in analysis function to calculate MSDs
  .appveyor.yml
  .travis.yml
  package/CHANGELOG
  package/MDAnalysis/analysis/msd.py
  package/doc/sphinx/source/documentation_pages/analysis/msd.rst
  package/doc/sphinx/source/documentation_pages/analysis_modules.rst
  package/doc/sphinx/source/documentation_pages/references.rst
  package/doc/sphinx/source/images/msd_demo_plot.png
  package/setup.py
  testsuite/MDAnalysisTests/analysis/test_msd.py
  testsuite/setup.py
Labels: GSOC Starter

#2752 Remove py2 things from lib
  package/MDAnalysis/lib/NeighborSearch.py
  package/MDAnalysis/lib/__init__.py
  package/MDAnalysis/lib/correlations.py
  package/MDAnalysis/lib/distances.py
  package/MDAnalysis/lib/formats/__init__.py
  package/MDAnalysis/lib/formats/libdcd.pyx
  package/MDAnalysis/lib/log.py
  package/MDAnalysis/lib/mdamath.py
  package/MDAnalysis/lib/pkdtree.py
  package/MDAnalysis/lib/transformations.py
  package/MDAnalysis/lib/util.py
  testsuite/MDAnalysisTests/lib/test_augment.py
  testsuite/MDAnalysisTests/lib/test_cutil.py
  testsuite/MDAnalysisTests/lib/test_distances.py
  testsuite/MDAnalysisTests/lib/test_log.py
  testsuite/MDAnalysisTests/lib/test_neighborsearch.py
  testsuite/MDAnalysisTests/lib/test_nsgrid.py
  testsuite/MDAnalysisTests/lib/test_pkdtree.py
  testsuite/MDAnalysisTests/lib/test_util.py
Labels: remove-2.0

#2707 RDKitReader and RDKitParser
  .appveyor.yml
  .travis.yml
  package/CHANGELOG
  package/MDAnalysis/coordinates/RDKit.py
  package/MDAnalysis/coordinates/__init__.py
  package/MDAnalysis/core/selection.py
  package/MDAnalysis/core/topologyattrs.py
  package/MDAnalysis/core/universe.py
  package/MDAnalysis/topology/RDKitParser.py
  package/MDAnalysis/topology/__init__.py
  package/doc/sphinx/source/documentation_pages/topology/RDKitParser.rst
  package/doc/sphinx/source/documentation_pages/topology_modules.rst
  testsuite/MDAnalysisTests/coordinates/test_rdkit.py
  testsuite/MDAnalysisTests/core/test_atomselections.py
  testsuite/MDAnalysisTests/core/test_universe.py
  testsuite/MDAnalysisTests/data/molecule.sdf
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/MDAnalysisTests/topology/test_rdkit.py
Labels: Component-Topology

#2720 CI: add codecov to Azure CI
  azure-pipelines.yml
Labels: 32 bit, Continuous Integration, OpSys-Windows, testing
