Repository MDAnalysis/mdanalysis, pull requests merged in 2020-03, with the labels that each got.

#2549 test AnalysisFromFunction args order
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/base.py
  testsuite/MDAnalysisTests/analysis/test_base.py
Labels: GSOC Starter

#2552 Updated Readme
  README.rst
Labels: GSOC Starter

#2551 More flexibility with wildcards in selection
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/core/selection.py
  package/doc/sphinx/source/documentation_pages/selections.rst
  testsuite/MDAnalysisTests/core/test_atomselections.py
Labels: GSOC Starter

#2523 Created hole2 module
  package/CHANGELOG
  package/MDAnalysis/analysis/hole.py
  package/MDAnalysis/analysis/hole2/__init__.py
  package/MDAnalysis/analysis/hole2/hole.py
  package/MDAnalysis/analysis/hole2/templates.py
  package/MDAnalysis/analysis/hole2/utils.py
  package/doc/sphinx/source/documentation_pages/analysis/hole2.rst
  package/doc/sphinx/source/documentation_pages/analysis_modules.rst
  testsuite/MDAnalysisTests/analysis/test_hole2.py
Labels: Component-Analysis

#2561 fixed PCA align=True problems
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/pca.py
  testsuite/MDAnalysisTests/analysis/test_pca.py
Labels: GSOC Starter

#2589 Fix #2582: polymer persistence length example fix
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/polymer.py
Labels: GSOC Starter

#1862 Add Chemfiles as a coordinate reader/writer
  .appveyor.yml
  .travis.yml
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/coordinates/__init__.py
  package/MDAnalysis/coordinates/chemfiles.py
  package/doc/sphinx/source/documentation_pages/coordinates/chemfiles.rst
  package/doc/sphinx/source/documentation_pages/coordinates_modules.rst
  testsuite/MDAnalysisTests/coordinates/base.py
  testsuite/MDAnalysisTests/coordinates/test_chemfiles.py
  testsuite/MDAnalysisTests/coordinates/test_xyz.py
Labels: Component-Readers, Work in progress

#2607 Importing ABCs from `collections.abc`
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/lib/util.py
Labels: GSOC Starter

#2611 Read XDR offsets from trajectory if file read-in fails
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/coordinates/XDR.py
  testsuite/MDAnalysisTests/coordinates/test_xdr.py
Labels: GSOC Starter

#2616 Finalizing #2537
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/density.py
  testsuite/MDAnalysisTests/analysis/test_density.py
Labels: GSOC Starter

#2620 Update ClusterMethods.py 2575
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/encore/clustering/ClusteringMethod.py
  package/MDAnalysis/analysis/encore/clustering/cluster.py
  testsuite/MDAnalysisTests/analysis/test_encore.py
Labels: GSOC Starter

#2615 Fix #2606: moving local function to the top
  testsuite/MDAnalysisTests/analysis/test_encore.py
Labels: GSOC Starter

#2610 Weights rework for #2429
  package/CHANGELOG
  package/MDAnalysis/analysis/rms.py
  testsuite/MDAnalysisTests/analysis/test_rms.py
Labels: GSOC Starter

#2591 Fix #2590: Created new axes for plot of persistence_length.
  package/CHANGELOG
  package/MDAnalysis/analysis/polymer.py
  testsuite/MDAnalysisTests/analysis/test_persistencelength.py
Labels: GSOC Starter

#2617 tqdm ProgressBar implementation
  .appveyor.yml
  .travis.yml
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/base.py
  package/MDAnalysis/analysis/density.py
  package/MDAnalysis/analysis/hbonds/hbond_analysis.py
  package/MDAnalysis/analysis/hbonds/hbond_autocorrel.py
  package/MDAnalysis/analysis/helanal.py
  package/MDAnalysis/analysis/pca.py
  package/MDAnalysis/analysis/rms.py
  package/MDAnalysis/analysis/waterdynamics.py
  package/MDAnalysis/core/universe.py
  package/MDAnalysis/lib/log.py
  package/setup.py
  testsuite/MDAnalysisTests/analysis/test_base.py
  testsuite/MDAnalysisTests/analysis/test_rms.py
  testsuite/MDAnalysisTests/lib/test_log.py
Labels: GSOC Starter

#2614 issue #2469
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/align.py
  package/MDAnalysis/analysis/rms.py
  package/MDAnalysis/lib/util.py
  package/MDAnalysis/transformations/fit.py
  testsuite/MDAnalysisTests/analysis/test_align.py
  testsuite/MDAnalysisTests/analysis/test_rms.py
  testsuite/MDAnalysisTests/lib/test_util.py
  testsuite/MDAnalysisTests/transformations/test_fit.py
Labels: GSOC Starter

#2634 Updated mdamath
  package/CHANGELOG
  package/MDAnalysis/lib/mdamath.py
  testsuite/MDAnalysisTests/lib/test_util.py
Labels: GSOC Starter

#2627 Providing Elements attribute to parsers (#2553)
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/topology/PDBParser.py
  testsuite/MDAnalysisTests/topology/test_pdb.py
Labels: GSOC Starter
