Repository MDAnalysis/mdanalysis, pull requests merged in 2020-01, with the labels that each got.

#2441 TST: pin NumPy version for Travis MacOS
  .travis.yml
Labels: OpSys-OSX, testing

#2447 TST: pin setuptools in Python 2.7 CI
  .travis.yml
Labels: testing

#2430 align.AverageStructure for out-of-memory average structures
  package/CHANGELOG
  package/MDAnalysis/analysis/align.py
  testsuite/MDAnalysisTests/analysis/test_align.py
Labels: Component-Analysis, enhancement

#2408 Modifications to ITPParser
  package/CHANGELOG
  package/MDAnalysis/topology/ITPParser.py
  package/MDAnalysis/topology/base.py
  testsuite/MDAnalysisTests/data/bad_top.top
  testsuite/MDAnalysisTests/data/edited_itp.itp
  testsuite/MDAnalysisTests/data/gromacs/gromos54a7_edited.ff/ff_dum.itp
  testsuite/MDAnalysisTests/data/gromacs/gromos54a7_edited.ff/ffbonded.itp
  testsuite/MDAnalysisTests/data/gromacs/gromos54a7_edited.ff/ffnonbonded.itp
  testsuite/MDAnalysisTests/data/gromacs/gromos54a7_edited.ff/forcefield.itp
  testsuite/MDAnalysisTests/data/gromacs/gromos54a7_edited.ff/ions.itp
  testsuite/MDAnalysisTests/data/gromacs/gromos54a7_edited.ff/spc.itp
  testsuite/MDAnalysisTests/data/gromacs_ala10.top
  testsuite/MDAnalysisTests/data/no_endif_spc.itp
  testsuite/MDAnalysisTests/data/spce.itp
  testsuite/MDAnalysisTests/data/tip5p.itp
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/MDAnalysisTests/topology/test_itp.py
Labels: Component-Topology

#2482 Removing deprecated reader code for v1.0
  package/CHANGELOG
  package/MDAnalysis/coordinates/TRJ.py
  testsuite/MDAnalysisTests/coordinates/test_netcdf.py
Labels: Component-Readers, Format-Amber

#2483 added parmed to setup.py
  package/CHANGELOG
  package/setup.py
Labels: installation
