Repository MDAnalysis/mdanalysis, pull requests merged in 2020-10, with the labels that each got.

#2960 Add more docs redirects
  maintainer/update_json_stubs_sitemap.py
Labels: Component-Docs

#2955 Write more redirect stubs
  maintainer/update_json_stubs_sitemap.py
Labels: Component-Docs

#2885 MAINT: fix invalid escape seqs
  package/CHANGELOG
  package/MDAnalysis/analysis/data/filenames.py
  package/MDAnalysis/analysis/dihedrals.py
  package/MDAnalysis/analysis/encore/clustering/ClusterCollection.py
  package/MDAnalysis/analysis/encore/confdistmatrix.py
  package/MDAnalysis/analysis/encore/covariance.py
  package/MDAnalysis/analysis/encore/similarity.py
  package/MDAnalysis/analysis/encore/utils.py
  package/MDAnalysis/analysis/gnm.py
  package/MDAnalysis/analysis/hole2/hole.py
  package/MDAnalysis/analysis/hole2/templates.py
  package/MDAnalysis/analysis/hole2/utils.py
  package/MDAnalysis/coordinates/H5MD.py
  package/MDAnalysis/core/groups.py
  package/MDAnalysis/core/selection.py
  package/MDAnalysis/core/topologyattrs.py
  package/MDAnalysis/lib/distances.py
  package/MDAnalysis/lib/transformations.py
  package/MDAnalysis/lib/util.py
  testsuite/MDAnalysisTests/analysis/test_density.py
  testsuite/MDAnalysisTests/analysis/test_hydrogenbonds_analysis.py
  testsuite/MDAnalysisTests/core/test_fragments.py
  testsuite/MDAnalysisTests/util.py
  testsuite/MDAnalysisTests/utils/test_meta.py
  testsuite/setup.cfg
Labels: maintainability

#2981 Use a fixture for npz files in test_bat
  package/CHANGELOG
  testsuite/MDAnalysisTests/analysis/test_bat.py
Labels: Component-Analysis, testing

#2983 Have CI use mamba
  .travis.yml
  package/CHANGELOG
Labels: Continuous Integration

#2992 Fixes AtomGroup.center when using compounds + unwrapping
  package/CHANGELOG
  package/MDAnalysis/core/groups.py
  testsuite/MDAnalysisTests/core/test_atomgroup.py
Labels: PBC, Priority-High, defect

#2956 TST, CI: add ARM64 Graviton 2 to CI
  .travis.yml
  package/setup.py
  testsuite/MDAnalysisTests/formats/test_libdcd.py
Labels: Continuous Integration, arch:ARMv8, testing

#2997 MAINT: ARM64 CI cleanup
  .travis.yml
  package/CHANGELOG
Labels: Continuous Integration, arch:ARMv8, maintainability

#2427 Always transplant a stub for transplanted methods
  maintainer/conda/MDAnalysis/meta.yaml
  package/CHANGELOG
  package/MDAnalysis/core/groups.py
  package/MDAnalysis/core/topologyattrs.py
  package/doc/sphinx/source/documentation_pages/references.rst
  package/setup.py
  testsuite/MDAnalysisTests/core/test_topologyattrs.py
  testsuite/MDAnalysisTests/transformations/test_translate.py
Labels: Component-Core, Component-Docs

#3008 removed funcsigs (not needed for Py >= 3.6)
  package/MDAnalysis/core/topologyattrs.py
  package/setup.py
Labels: refactoring

#2998 Smoothen analysis class docstrings
  package/CHANGELOG
  package/MDAnalysis/analysis/__init__.py
  package/MDAnalysis/analysis/dihedrals.py
  package/MDAnalysis/analysis/helix_analysis.py
  package/MDAnalysis/analysis/hole2/hole.py
  package/MDAnalysis/analysis/hydrogenbonds/hbond_analysis.py
  package/MDAnalysis/analysis/lineardensity.py
  package/MDAnalysis/analysis/msd.py
  package/MDAnalysis/analysis/pca.py
  package/MDAnalysis/analysis/rdf.py
Labels: Component-Docs

#3012 Cleanup and better parametrization of test_atomgroup.py
  package/CHANGELOG
  testsuite/MDAnalysisTests/core/test_atomgroup.py
Labels: testing
