Repository MDAnalysis/mdanalysis, pull requests merged in 2021-04, with the labels that each got.

#3154 Fixed issue -3148 (#3154) Warn user grid ignored DensityAnalysis
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/density.py
  testsuite/MDAnalysisTests/analysis/test_density.py
Labels: GSOC Starter

#3172 Deprecate ParmedConverter taking Timestep objects
  package/CHANGELOG
  package/MDAnalysis/coordinates/ParmEd.py
  testsuite/MDAnalysisTests/coordinates/test_parmed.py
Labels: release-1.1

#3160 Added get_connections
  package/CHANGELOG
  package/MDAnalysis/core/groups.py
  package/MDAnalysis/core/topologyattrs.py
  testsuite/MDAnalysisTests/core/test_groups.py
Labels: Priority-High, release-1.1

#3194 Deprecation warning for results attribute
  package/CHANGELOG
  package/MDAnalysis/analysis/base.py
  package/MDAnalysis/analysis/gnm.py
  package/MDAnalysis/analysis/lineardensity.py
  package/MDAnalysis/analysis/polymer.py
  testsuite/MDAnalysisTests/analysis/test_base.py
  testsuite/MDAnalysisTests/analysis/test_gnm.py
  testsuite/MDAnalysisTests/analysis/test_lineardensity.py
  testsuite/MDAnalysisTests/analysis/test_persistencelength.py
Labels: release-1.1

#3212 Undo half of PR 3160
  package/CHANGELOG
  package/MDAnalysis/core/topologyattrs.py
  testsuite/MDAnalysisTests/core/test_groups.py
Labels: Priority-High, release-1.1

#3202 Fixes sphzone, sphlayer, cyzone, cylayer empty selections
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/core/selection.py
  testsuite/MDAnalysisTests/core/test_atomselections.py
Labels: Component-Selections, GSOC Starter

#3134 Fixes RMSD weights_groupselections docstring
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/rms.py
Labels: GSOC Starter

#3175 Add Transformation to set box dimensions
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/transformations/__init__.py
  package/MDAnalysis/transformations/boxdimensions.py
  package/doc/sphinx/source/documentation_pages/trajectory_transformations.rst
  package/doc/sphinx/source/documentation_pages/transformations/boxdimensions.rst
  testsuite/MDAnalysisTests/transformations/test_boxdimensions.py
Labels: Component-Transformations, GSOC Starter

#3027 MAINT, CI: Azure add Python 3.9 Win
  azure-pipelines.yml
Labels: Continuous Integration, maintainability

#3178 Removes deprecated sklearn arguments from encore
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/encore/clustering/ClusteringMethod.py
  testsuite/MDAnalysisTests/analysis/test_encore.py
Labels: GSOC Starter

#3157 Write out chainID to PDB instead of segID
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/coordinates/PDB.py
  testsuite/MDAnalysisTests/coordinates/test_pdb.py
Labels: GSOC Starter

#3188 Add sort method to AtomGroup
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/core/groups.py
  testsuite/MDAnalysisTests/core/test_atomgroup.py
Labels: GSOC Starter

#3156 Fixes Issue #3124
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/align.py
  testsuite/MDAnalysisTests/analysis/test_align.py
Labels: GSOC Starter

#3108 Use absolute file paths in ITPParser
  package/CHANGELOG
  package/MDAnalysis/topology/ITPParser.py
  testsuite/MDAnalysisTests/data/gromacs/gromos54a7_edited.ff/test.itp
  testsuite/MDAnalysisTests/topology/test_itp.py
Labels: GSOC Starter

#2926 Aromaticity and Gasteiger charges guessers
  package/MDAnalysis/topology/guessers.py
  testsuite/MDAnalysisTests/topology/test_guessers.py
Labels: GSoC

#3234 BLD: handle gcc on MacOS
  package/setup.py
Labels: installation
