Repository MDAnalysis/mdanalysis, pull requests merged in 2021-03, with the labels that each got.

#3135 Implements cache validation at the Universe level
  .gitignore
  benchmarks/benchmarks/ag_methods.py
  package/CHANGELOG
  package/MDAnalysis/core/topologyattrs.py
  package/MDAnalysis/core/universe.py
  package/MDAnalysis/lib/util.py
  testsuite/MDAnalysisTests/core/test_fragments.py
  testsuite/MDAnalysisTests/lib/test_util.py
Labels: Component-Core, enhancement

#3091 Emit warnings for empty Ag and user grid in DensityAnalysis
  package/CHANGELOG
  package/MDAnalysis/analysis/density.py
  testsuite/MDAnalysisTests/analysis/test_density.py
Labels: Component-Analysis, GSOC Starter, defect

#3128 updated CHEMFILES docs
  package/MDAnalysis/coordinates/__init__.py
  package/MDAnalysis/coordinates/chemfiles.py
Labels: Component-Docs, Component-Readers, Component-Writers

#3111 deprecate hydrogen bond analysis in water bridge analysis to master
  package/CHANGELOG
  package/MDAnalysis/analysis/hbonds/wbridge_analysis.py
  package/MDAnalysis/analysis/hydrogenbonds/__init__.py
  package/MDAnalysis/analysis/hydrogenbonds/wbridge_analysis.py
  package/doc/sphinx/source/documentation_pages/analysis/wbridge_analysis.rst
  testsuite/MDAnalysisTests/analysis/test_wbridge.py
Labels: deprecation

#3153 Add tpr_resid_from_one keyword to TPRParser
  package/CHANGELOG
  package/MDAnalysis/topology/TPRParser.py
  package/MDAnalysis/topology/tpr/utils.py
  testsuite/MDAnalysisTests/topology/test_tprparser.py
Labels: Priority-High, release-1.1

#3162 Use match to check hole2 warnings
  testsuite/MDAnalysisTests/analysis/test_hole2.py
Labels: Priority-High, release-1.1

#3163 Adds test to make sure small box issue is now fixed #2670
  package/CHANGELOG
  testsuite/MDAnalysisTests/lib/test_nsgrid.py
Labels: Priority-High, release-1.1

#3155 Adds test for datafiles import to cover failed import
  testsuite/MDAnalysisTests/utils/test_datafiles.py
Labels: testing

#3130 Fixed issue -3129
  package/CHANGELOG
  package/setup.py
Labels: Priority-High, release-1.1

#3173 Deprecate using segid for chainid
  package/CHANGELOG
  package/MDAnalysis/coordinates/PDB.py
  testsuite/MDAnalysisTests/coordinates/test_pdb.py
Labels: release-1.1

#3184 Create Universe from empty RDKit ROMol
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/topology/RDKitParser.py
  testsuite/MDAnalysisTests/core/test_universe.py
Labels: Component-Topology, GSOC Starter

#3185 Issue 2327 - Warn of upcoming scale_factor changes
  package/CHANGELOG
  package/MDAnalysis/coordinates/TRJ.py
  testsuite/MDAnalysisTests/coordinates/test_netcdf.py
Labels: Priority-High, release-1.1

#3186 improved FastNS performance for orthorhombic boxes
  package/MDAnalysis/lib/include/calc_distances.h
  package/MDAnalysis/lib/nsgrid.cpp
  package/MDAnalysis/lib/nsgrid.pyx
Labels: Priority-High, release-1.1
