Repository MDAnalysis/mdanalysis, pull requests merged in 2021-12, with the labels that each got.

#3482 More details on Dihedral doc
  package/MDAnalysis/analysis/dihedrals.py
Labels: Component-Analysis

#3461 CI: add Win 3.10
  azure-pipelines.yml
  testsuite/MDAnalysisTests/coordinates/test_chainreader.py
  testsuite/MDAnalysisTests/coordinates/test_h5md.py
  testsuite/MDAnalysisTests/topology/test_top.py
  testsuite/MDAnalysisTests/utils/test_duecredit.py
Labels: OpSys-Windows, Continuous Integration

#3445 Rs chirality
  package/CHANGELOG
  package/MDAnalysis/converters/RDKitParser.py
  package/MDAnalysis/core/groups.py
  package/MDAnalysis/core/selection.py
  package/MDAnalysis/core/topologyattrs.py
  package/doc/sphinx/source/documentation_pages/selections.rst
  testsuite/MDAnalysisTests/converters/test_rdkit_parser.py
  testsuite/MDAnalysisTests/core/test_atomselections.py
Labels: Component-Core, Component-Converters

#3454 Make HydrogenBondAnalysis handle empty selection strings
  package/CHANGELOG
  package/MDAnalysis/analysis/hydrogenbonds/hbond_analysis.py
  testsuite/MDAnalysisTests/analysis/test_hydrogenbonds_analysis.py
Labels: Component-Analysis

#3466 add parse_n_atoms() to H5MDReader
  package/CHANGELOG
  package/MDAnalysis/coordinates/H5MD.py
  testsuite/MDAnalysisTests/coordinates/test_h5md.py
Labels: Component-Readers

#3488 Defaults TRZReader timestep to 1.0 ps
  package/CHANGELOG
  package/MDAnalysis/coordinates/TRZ.py
  testsuite/MDAnalysisTests/coordinates/test_trz.py
Labels: Component-Readers

#3458 Add minimal deps py3.10 to linux CI matrix
  .github/workflows/gh-ci.yaml
  testsuite/MDAnalysisTests/coordinates/test_chainreader.py
  testsuite/MDAnalysisTests/topology/test_top.py
Labels: OpSys-Linux
