Repository MDAnalysis/mdanalysis, pull requests merged in 2022-10, with the labels that each got.

#3846 Add isolayer selection method
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/core/groups.py
  package/MDAnalysis/core/selection.py
  package/doc/sphinx/source/documentation_pages/selections.rst
  testsuite/MDAnalysisTests/core/test_atomselections.py
Labels: Component-Core

#3839 Empty atomgroup
  package/CHANGELOG
  package/MDAnalysis/core/topologyattrs.py
  package/MDAnalysis/lib/util.py
  testsuite/MDAnalysisTests/core/test_groups.py
  testsuite/MDAnalysisTests/lib/test_util.py
Labels: Component-Core, Component-lib

#3859 Pin 32bit Windows Azure runner to 1.9.1
  azure-pipelines.yml
Labels: Continuous Integration

#3868 Add rmsip docs
  package/MDAnalysis/analysis/pca.py
  package/doc/sphinx/source/conf.py
Labels: Component-Docs, Component-Analysis

#3876 Access hbonds results through new results member in count_by_ids() and count_by_type()
  package/CHANGELOG
  package/MDAnalysis/analysis/hydrogenbonds/hbond_analysis.py
Labels: Component-Analysis

#3884 Add annotate cython setup.cfg option
  package/setup.cfg
  package/setup.py
Labels: installation

#3844 Lammps Dump Parser
  package/CHANGELOG
  package/MDAnalysis/coordinates/LAMMPS.py
  testsuite/MDAnalysisTests/coordinates/test_lammps.py
  testsuite/MDAnalysisTests/data/lammps/image_vf.data
  testsuite/MDAnalysisTests/data/lammps/image_vf.lammpstrj
  testsuite/MDAnalysisTests/datafiles.py
Labels: Component-Readers

#3832 Fixed lockfile check when using a Docker read-only filesystem
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/coordinates/XDR.py
Labels: Component-Readers

#3886 Fix 32bit azure
  azure-pipelines.yml
Labels: Continuous Integration
