Repository MDAnalysis/mdanalysis, pull requests merged in 2023-12, with the labels that each got.

#4352 Update benchmarks default python in asv.conf.json
  benchmarks/asv.conf.json
Labels: performance

#4360 BENCH: fix time_geometric_selections
  benchmarks/benchmarks/selections.py
Labels: performance, benchmarks

#4346 Updated cimport for numpy to maintain cimport consistency
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/encore/cutils.pyx
  package/MDAnalysis/coordinates/timestep.pyx
  package/MDAnalysis/lib/_augment.pyx
  package/MDAnalysis/lib/_cutil.pyx
  package/MDAnalysis/lib/formats/cython_util.pxd
  package/MDAnalysis/lib/formats/cython_util.pyx
  package/MDAnalysis/lib/formats/libdcd.pxd
  package/MDAnalysis/lib/formats/libdcd.pyx
  package/MDAnalysis/lib/formats/libmdaxdr.pxd
  package/MDAnalysis/lib/formats/libmdaxdr.pyx
  package/MDAnalysis/lib/qcprot.pyx
Labels: Component-Readers, Component-Analysis, Component-lib

#4361 [WIP] Fix authors & changelog
  package/AUTHORS
  package/CHANGELOG
Labels: Component-Docs

#4365 fix: errors due to ```make html```
  package/CHANGELOG
  package/MDAnalysis/coordinates/base.py
  package/doc/sphinx/source/conf.py
Labels: Component-Readers

#4368 DOC: CHANGELOG MM/DD/YY
  package/CHANGELOG
Labels: Component-Docs

#4369 MAINT: encore Windows type fixes
  package/MDAnalysis/analysis/encore/clustering/affinityprop.pyx
Labels: maintainability, OpSys-Windows, Component-Analysis

#4370 Fix: Transformations.py doctest errors
  package/CHANGELOG
  package/MDAnalysis/lib/transformations.py
Labels: Component-lib

#4367 TST, MAINT: test_frame_bool_fail compat
  testsuite/MDAnalysisTests/analysis/test_base.py
Labels: maintainability

#4292 GROMOS11 Reader
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/coordinates/TRC.py
  package/MDAnalysis/coordinates/__init__.py
  package/MDAnalysis/coordinates/chain.py
  package/doc/sphinx/source/documentation_pages/coordinates/TRC.rst
  package/doc/sphinx/source/documentation_pages/coordinates_modules.rst
  testsuite/MDAnalysisTests/coordinates/test_trc.py
  testsuite/MDAnalysisTests/data/gromos11/gromos11_cluster_vac.trj.gz
  testsuite/MDAnalysisTests/data/gromos11/gromos11_empty.trc
  testsuite/MDAnalysisTests/data/gromos11/gromos11_genbox_euler.trc.gz
  testsuite/MDAnalysisTests/data/gromos11/gromos11_genbox_origin.trc.gz
  testsuite/MDAnalysisTests/data/gromos11/gromos11_traj_solv.pdb.gz
  testsuite/MDAnalysisTests/data/gromos11/gromos11_traj_solv.trc.gz
  testsuite/MDAnalysisTests/data/gromos11/gromos11_traj_vac.pdb.gz
  testsuite/MDAnalysisTests/data/gromos11/gromos11_traj_vac_1.trc.gz
  testsuite/MDAnalysisTests/data/gromos11/gromos11_traj_vac_2.trc.gz
  testsuite/MDAnalysisTests/data/gromos11/gromos11_triclinic_solv.trc.gz
  testsuite/MDAnalysisTests/data/gromos11/gromos11_truncOcta_vac.trc.gz
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/MDAnalysisTests/parallelism/test_multiprocessing.py
  testsuite/setup.py
Labels: enhancement, Component-Readers, Format-GROMOS, new-feature

#4366 Two doctest fixes
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/analysis/atomicdistances.py
  package/doc/sphinx/source/documentation_pages/overview.rst
Labels: Component-Analysis

#4375 Update README to reflect move to GitHub Discussions
  .github/ISSUE_TEMPLATE/questions.md
  .github/workflows/greetings.yaml
  CODE_OF_CONDUCT.md
  GOVERNANCE.md
  README.rst
  package/INSTALL
  package/MDAnalysis/__init__.py
  package/MDAnalysis/coordinates/TRJ.py
  package/README
  package/doc/README
  package/doc/sphinx/source/index.rst
  package/setup.py
  testsuite/INSTALL
  testsuite/README
  testsuite/setup.py
Labels: Component-Readers

#4329 Adding py3.12 to full dependency CI checks
  .github/workflows/gh-ci.yaml
Labels: maintainability

#4392 Change the target build names for cibuildwheels for cirrus
  maintainer/ci/cirrus-deploy.yml
Labels: Continuous Integration

#4394 Add Cython 3.0.7 generated files
  package/MDAnalysis/analysis/encore/clustering/affinityprop.c
  package/MDAnalysis/analysis/encore/cutils.c
  package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.c
  package/MDAnalysis/coordinates/timestep.cpp
  package/MDAnalysis/lib/_augment.cpp
  package/MDAnalysis/lib/_cutil.cpp
  package/MDAnalysis/lib/c_distances.c
  package/MDAnalysis/lib/c_distances_openmp.c
  package/MDAnalysis/lib/formats/cython_util.c
  package/MDAnalysis/lib/formats/libdcd.c
  package/MDAnalysis/lib/formats/libmdaxdr.c
  package/MDAnalysis/lib/nsgrid.cpp
  package/MDAnalysis/lib/qcprot.c
Labels: Component-Readers, Component-Analysis, Component-lib
