Repository MDAnalysis/mdanalysis, pull requests merged in 2023-05, with the labels that each got.

#4135 update CoC with option to report to NumFOCUS
  CODE_OF_CONDUCT.md
Labels: Component-Docs

#4066 Fix the case where distance_type = 'heavy' in water bridge analysis
  package/CHANGELOG
  package/MDAnalysis/analysis/hydrogenbonds/wbridge_analysis.py
  testsuite/MDAnalysisTests/analysis/test_wbridge.py
Labels: Component-Analysis

#4114 Add writing u.trajectory.ts.data['molecule_tag'] as molecule_tag atom attribute to LAMMPS datafile
  package/CHANGELOG
  package/MDAnalysis/coordinates/LAMMPS.py
  testsuite/MDAnalysisTests/coordinates/test_lammps.py
Labels: Component-Readers

#4147 Revert "Temporarily pin chemfiles to <0.10.4"
  azure-pipelines.yml
Labels: Continuous Integration

#4056 Switching to importlib resources
  azure-pipelines.yml
  testsuite/MDAnalysisTests/data/__init__.py
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/MDAnalysisTests/utils/test_datafiles.py
Labels: Continuous Integration

#3988 taking a swing at #3825
  package/CHANGELOG
  package/MDAnalysis/coordinates/PDB.py
  testsuite/MDAnalysisTests/coordinates/test_pdb.py
  testsuite/MDAnalysisTests/data/varying_occ_tmp.pdb
  testsuite/MDAnalysisTests/datafiles.py
Labels: Component-Readers

#3906 ChainReader now subclasses BaseReader
  package/CHANGELOG
  package/MDAnalysis/coordinates/base.py
  package/MDAnalysis/coordinates/chain.py
  testsuite/MDAnalysisTests/coordinates/test_chainreader.py
  testsuite/MDAnalysisTests/coordinates/test_copying.py
Labels: Component-Readers

#4140 Add kwarg n_frames to Universe.empty() (#4110)
  package/CHANGELOG
  package/MDAnalysis/core/universe.py
  testsuite/MDAnalysisTests/core/test_universe.py
Labels: Component-Core

#4082 RDKitConverter improvements
  package/CHANGELOG
  package/MDAnalysis/converters/RDKit.py
  testsuite/MDAnalysisTests/converters/test_rdkit.py
Labels: Component-Converters

#4150 Cirrus deploy wheels
  .cirrus.star
  maintainer/ci/cirrus-deploy.yml
  package/CHANGELOG
Labels: Continuous Integration

#4154 [DEPEND #4150] Prerelease 2.5.0
  maintainer/conda/MDAnalysis/meta.yaml
  package/CHANGELOG
  package/MDAnalysis/version.py
  package/setup.py
  testsuite/MDAnalysisTests/__init__.py
  testsuite/setup.py
Labels: Continuous Integration

#4155 Add Cython 0.29.35 generated files
  package/MDAnalysis/analysis/encore/clustering/affinityprop.c
  package/MDAnalysis/analysis/encore/cutils.c
  package/MDAnalysis/analysis/encore/dimensionality_reduction/stochasticproxembed.c
  package/MDAnalysis/coordinates/timestep.cpp
  package/MDAnalysis/lib/_augment.cpp
  package/MDAnalysis/lib/_cutil.cpp
  package/MDAnalysis/lib/c_distances.c
  package/MDAnalysis/lib/c_distances_openmp.c
  package/MDAnalysis/lib/formats/cython_util.c
  package/MDAnalysis/lib/formats/libdcd.c
  package/MDAnalysis/lib/formats/libmdaxdr.c
  package/MDAnalysis/lib/nsgrid.cpp
  package/MDAnalysis/lib/qcprot.c
Labels: Component-Readers, Component-Analysis, Component-lib

#4157 Start 2.6.0-dev0
  maintainer/conda/MDAnalysis/meta.yaml
  package/CHANGELOG
  package/MDAnalysis/version.py
  package/setup.py
  testsuite/MDAnalysisTests/__init__.py
  testsuite/setup.py
Labels: Continuous Integration
