Repository MDAnalysis/mdanalysis, pull requests merged in 2024-12, with the labels that each got.

#4747 add default None -> UserWarning
  testsuite/MDAnalysisTests/topology/test_itp.py
  testsuite/MDAnalysisTests/util.py
Labels: maintainability, testing

#4727 'MDAnalysis.analysis.nucleicacids' parallelization
  package/CHANGELOG
  package/MDAnalysis/analysis/nucleicacids.py
  testsuite/MDAnalysisTests/analysis/conftest.py
  testsuite/MDAnalysisTests/analysis/test_nucleicacids.py
Labels: parallelization

#4866 ENH: support tpx 134 (GMX 2024.4)
  package/CHANGELOG
  package/MDAnalysis/topology/TPRParser.py
  package/MDAnalysis/topology/tpr/setting.py
  package/MDAnalysis/topology/tpr/utils.py
  testsuite/MDAnalysisTests/data/tprs/2lyz_gmx_2024_4.tpr
  testsuite/MDAnalysisTests/data/tprs/all_bonded/dummy_2024_4.tpr
  testsuite/MDAnalysisTests/data/tprs/virtual_sites/extra-interactions-2024_4.tpr
  testsuite/MDAnalysisTests/datafiles.py
  testsuite/MDAnalysisTests/topology/test_tprparser.py
Labels: enhancement, Format-Gromacs
