Repository MDAnalysis/mdanalysis, pull requests merged in 2024-02, with the labels that each got.

#4407 ChainedReader __repr__ fix for MemoryReader sub-readers
  package/CHANGELOG
  package/MDAnalysis/coordinates/chain.py
  testsuite/MDAnalysisTests/coordinates/test_chainreader.py
Labels: Component-Readers

#4424 Cleaning up packaging for `package`
  package/CHANGELOG
  package/MDAnalysis/lib/formats/include/__init__.py
  package/MDAnalysis/lib/formats/src/__init__.py
  package/MDAnalysis/lib/include/__init__.py
  package/MDAnalysis/lib/libmdanalysis/__init__.py
  package/MDAnalysis/lib/src/transformations/__init__.py
  package/pyproject.toml
  package/setup.py
Labels: Component-lib

#4438 Replaced numpy.testing.assert_almost_equal to numpy.testing.assert_allclose
  package/AUTHORS
  package/CHANGELOG
  package/MDAnalysis/visualization/streamlines_3D.py
  testsuite/MDAnalysisTests/analysis/test_align.py
  testsuite/MDAnalysisTests/analysis/test_base.py
  testsuite/MDAnalysisTests/analysis/test_bat.py
  testsuite/MDAnalysisTests/analysis/test_contacts.py
  testsuite/MDAnalysisTests/analysis/test_dihedrals.py
  testsuite/MDAnalysisTests/analysis/test_encore.py
Labels: maintainability, testing
